import { dateDaysAgo, timestampOn } from "./dates";
import type { Workspace } from "./types";

export function createSeed(now = new Date()): Workspace {
  const sentAlma = dateDaysAgo(18, now);
  const sentVetor = dateDaysAgo(3, now);
  const sentLumina = dateDaysAgo(5, now);
  const sentCalha = dateDaysAgo(20, now);
  const draftPrado = dateDaysAgo(1, now);

  return {
    company: {
      name: "L² Soluções",
      document: "00.000.000/0001-91",
      email: "contato@l2solucoes.com.br",
      phone: "(11) 98800-2210",
      city: "São Paulo, SP",
      pix: "contato@l2solucoes.com.br",
      site: "https://l2solucoes.com.br",
    },
    clients: [
      {
        id: "cli_alma",
        name: "Marina Alves",
        company: "Clínica Alma",
        email: "marina@clinicaalma.example",
        phone: "(11) 98821-4400",
        city: "São Paulo, SP",
        createdAt: timestampOn(dateDaysAgo(40, now), 9),
      },
      {
        id: "cli_vetor",
        name: "Ricardo Penteado",
        company: "Oficina Vetor",
        email: "ricardo@oficinavetor.example",
        phone: "(19) 99120-8833",
        city: "Campinas, SP",
        createdAt: timestampOn(dateDaysAgo(21, now), 10),
      },
      {
        id: "cli_lumina",
        name: "Helena Duarte",
        company: "Agência Lumina",
        email: "helena@agencialumina.example",
        phone: "(41) 98440-2291",
        city: "Curitiba, PR",
        createdAt: timestampOn(dateDaysAgo(12, now), 11),
      },
      {
        id: "cli_prado",
        name: "Paulo Nogueira",
        company: "Escritório Prado",
        email: "paulo@prado.example",
        phone: "(31) 98770-1144",
        city: "Belo Horizonte, MG",
        createdAt: timestampOn(dateDaysAgo(4, now), 15),
      },
      {
        id: "cli_calha",
        name: "João Ferraz",
        company: "Studio Calha",
        email: "joao@studiocalha.example",
        phone: "(48) 99910-7720",
        city: "Florianópolis, SC",
        createdAt: timestampOn(dateDaysAgo(30, now), 14),
      },
    ],
    proposals: [
      {
        id: "pro_alma",
        number: "PR-2026-014",
        token: "alma-agenda-k7m",
        clientId: "cli_alma",
        title: "Portal de agendamento e confirmação",
        summary:
          "A paciente escolhe o horário no site e a recepção confirma pelo painel, sem a troca de mensagens que hoje trava a agenda.",
        items: [
          {
            id: "it_alma_1",
            description: "Descoberta do fluxo de recepção e agenda",
            quantity: 1,
            unitPriceCents: 280_000,
          },
          {
            id: "it_alma_2",
            description: "Portal do paciente com escolha de horário",
            quantity: 1,
            unitPriceCents: 960_000,
          },
          {
            id: "it_alma_3",
            description: "Painel da recepção para confirmar e remarcar",
            quantity: 1,
            unitPriceCents: 720_000,
          },
          {
            id: "it_alma_4",
            description: "Treinamento da equipe",
            quantity: 1,
            unitPriceCents: 80_000,
          },
        ],
        discountPercent: 0,
        validityDays: 10,
        validUntil: dateDaysAgo(8, now),
        paymentTerms: "40% na aprovação, 40% na entrega do painel e 20% na publicação.",
        notes: "Horários, profissionais e convênios desta versão. Integração com prontuário fica para uma etapa seguinte.",
        status: "aceita",
        createdAt: timestampOn(dateDaysAgo(20, now), 9),
        updatedAt: timestampOn(dateDaysAgo(12, now), 16),
        sentAt: timestampOn(sentAlma, 10),
        viewedAt: timestampOn(dateDaysAgo(17, now), 19),
        respondedAt: timestampOn(dateDaysAgo(12, now), 16),
        responseName: "Marina Alves",
        responseNote: "Podemos começar na primeira semana de outubro.",
      },
      {
        id: "pro_vetor",
        number: "PR-2026-021",
        token: "vetor-os-q3p",
        clientId: "cli_vetor",
        title: "Painel de ordens de serviço",
        summary:
          "Cada carro entra como uma OS, do orçamento à entrega. O cliente acompanha o status por um link, em vez de ligar para a oficina.",
        items: [
          {
            id: "it_vetor_1",
            description: "Mapeamento do fluxo da oficina",
            quantity: 1,
            unitPriceCents: 180_000,
          },
          {
            id: "it_vetor_2",
            description: "Painel de ordens de serviço",
            quantity: 1,
            unitPriceCents: 890_000,
          },
          {
            id: "it_vetor_3",
            description: "Página de acompanhamento para o cliente",
            quantity: 1,
            unitPriceCents: 320_000,
          },
        ],
        discountPercent: 5,
        validityDays: 10,
        validUntil: dateDaysAgo(-7, now),
        paymentTerms: "50% na aprovação e 50% na entrega.",
        notes: "O desconto vale para início ainda neste mês.",
        status: "visualizada",
        createdAt: timestampOn(dateDaysAgo(6, now), 11),
        updatedAt: timestampOn(dateDaysAgo(1, now), 18),
        sentAt: timestampOn(sentVetor, 11),
        viewedAt: timestampOn(dateDaysAgo(1, now), 18),
        respondedAt: null,
        responseName: null,
        responseNote: null,
      },
      {
        id: "pro_lumina",
        number: "PR-2026-022",
        token: "lumina-site-b8d",
        clientId: "cli_lumina",
        title: "Site institucional com página de serviços",
        summary:
          "Um site curto para a agência apresentar serviços, cases e um briefing inicial. Sem blog e sem área de cliente nesta etapa.",
        items: [
          {
            id: "it_lumina_1",
            description: "Site de até 6 páginas",
            quantity: 1,
            unitPriceCents: 640_000,
          },
          {
            id: "it_lumina_2",
            description: "Formulário de briefing",
            quantity: 1,
            unitPriceCents: 180_000,
          },
          {
            id: "it_lumina_3",
            description: "Publicação e orientação de domínio",
            quantity: 1,
            unitPriceCents: 140_000,
          },
        ],
        discountPercent: 0,
        validityDays: 7,
        validUntil: dateDaysAgo(-2, now),
        paymentTerms: "60% na aprovação e 40% na publicação.",
        notes: "Textos e fotos ficam por conta da agência. A L² orienta a estrutura.",
        status: "enviada",
        createdAt: timestampOn(dateDaysAgo(5, now), 9),
        updatedAt: timestampOn(sentLumina, 9),
        sentAt: timestampOn(sentLumina, 9),
        viewedAt: null,
        respondedAt: null,
        responseName: null,
        responseNote: null,
      },
      {
        id: "pro_prado",
        number: "PR-2026-023",
        token: "prado-portal-n2c",
        clientId: "cli_prado",
        title: "Portal do cliente para acompanhamento",
        summary:
          "O cliente do escritório entra com um código e vê o andamento do que foi contratado, sem pedir atualização por e-mail.",
        items: [
          {
            id: "it_prado_1",
            description: "Arquitetura e acesso por cliente",
            quantity: 1,
            unitPriceCents: 420_000,
          },
          {
            id: "it_prado_2",
            description: "Portal com linha do tempo de andamentos",
            quantity: 1,
            unitPriceCents: 1_280_000,
          },
          {
            id: "it_prado_3",
            description: "Aviso por e-mail a cada atualização",
            quantity: 1,
            unitPriceCents: 360_000,
          },
        ],
        discountPercent: 0,
        validityDays: 15,
        validUntil: null,
        paymentTerms: "30% na aprovação, 40% no portal interno e 30% na publicação.",
        notes: "Rascunho interno. Ainda falta fechar se o aviso sai por e-mail ou WhatsApp.",
        status: "rascunho",
        createdAt: timestampOn(draftPrado, 16),
        updatedAt: timestampOn(draftPrado, 17),
        sentAt: null,
        viewedAt: null,
        respondedAt: null,
        responseName: null,
        responseNote: null,
      },
      {
        id: "pro_calha",
        number: "PR-2026-011",
        token: "calha-landing-h4r",
        clientId: "cli_calha",
        title: "Landing e captação de orçamentos",
        summary:
          "Uma página única para o estúdio mostrar o trabalho e receber pedidos de orçamento com nome, prazo e tipo de peça.",
        items: [
          {
            id: "it_calha_1",
            description: "Landing de uma página",
            quantity: 1,
            unitPriceCents: 450_000,
          },
          {
            id: "it_calha_2",
            description: "Formulário de pedido de orçamento",
            quantity: 1,
            unitPriceCents: 120_000,
          },
        ],
        discountPercent: 10,
        validityDays: 7,
        validUntil: dateDaysAgo(13, now),
        paymentTerms: "100% na aprovação, para um escopo fechado de uma página.",
        notes: "Prazo de validade encerrado. Reenviar renova a data.",
        status: "enviada",
        createdAt: timestampOn(dateDaysAgo(22, now), 10),
        updatedAt: timestampOn(sentCalha, 10),
        sentAt: timestampOn(sentCalha, 10),
        viewedAt: timestampOn(dateDaysAgo(18, now), 20),
        respondedAt: null,
        responseName: null,
        responseNote: null,
      },
    ],
  };
}
